name: Connect to an AWS role from a GitHub repository

on:
  push:
    branches: 
      - '**'

env:
  AWS_REGION : "ap-south-1" 

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  # Job to run `terraform plan`
  plan:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Plan
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_accountId: ${{ secrets.ACCOUNT_ID }}
          TF_VAR_local_user_arn: ${{ secrets.LOCAL_USER_ARN }}
          TF_VAR_put_data_role_arn: ${{secrets.PUT_DATA_ROLE_ARN }}
        run: |
          terraform -chdir=terraform init
          terraform -chdir=terraform/ plan

  # Job to run `terraform apply`
  apply:
    runs-on: ubuntu-latest
    needs: plan  # This job depends on the successful completion of `plan`
    environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE_ARN}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Apply
        env:
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_accountId: ${{ secrets.ACCOUNT_ID }}
          TF_VAR_local_user_arn: ${{ secrets.LOCAL_USER_ARN }}
          TF_VAR_put_data_role_arn: ${{secrets.PUT_DATA_ROLE_ARN }}
        run: |
          terraform -chdir=terraform/ init
          terraform -chdir=terraform/ apply -auto-approve